import matplotlib.pyplot as plt
import numpy as np

scene = "cube60"
scene_file_path = f"../cache/flux_{scene}.npy"

def graph_flux_2d(file_path, axis, coord):
    f = np.load(file_path)

    if axis == "x":
        slice = f[coord, :, :]
    elif axis == "y":
        slice = f[:, coord, :]
    elif axis == "z":
        slice = f[:, :, coord]
    else:
        raise ValueError

    #if axis == "x":
    #    slice = f[coord][:][:]
    #elif axis == "y":
    #    slice = f[:][coord][:]
    #elif axis == "z":
    #    slice = f[:][:][coord]
    #else:
    #    raise ValueError

    slice += 1e-8
    log_10_data = np.log10(slice)

    plt.imshow(log_10_data, origin="lower")
    plt.show()

# graph_flux_2d(scene_file_path, "z", 0)


# function generated by Claude Opus 4.8
# detailed in docs/prompts, "Asked to build graph_flux_3d"
def graph_flux_3d(file_path):
    flux = np.load(file_path)
    if flux.ndim == 4:
        flux = flux[..., 0]

    # log scale (flux decays exponentially with depth)
    logflux = np.log10(flux + 1e-8)

    # pick a threshold to only show voxels with meaningful signal
    threshold = np.percentile(logflux, 90)
    filled = logflux > threshold

    # normalize for coloring
    norm = (logflux - logflux[filled].min()) / (logflux[filled].max() - logflux[filled].min())
    colors = plt.cm.viridis(np.clip(norm, 0, 1))
    colors[..., 3] = np.where(filled, 0.6, 0)  # alpha only where filled

    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(projection='3d')
    ax.voxels(filled, facecolors=colors, edgecolor=None)
    ax.set_xlabel('x');
    ax.set_ylabel('y');
    ax.set_zlabel('z')
    plt.tight_layout()
    plt.show()

# graph_flux_3d(scene_file_path)
