import json
import numpy as np
import matplotlib.pyplot as plt

# function generated by Claude Opus 4.8
# detailed in /docs/prompts, "Asked to build load_mcx_config in scripts/load_mcx_config.py"
def load_mcx_config(json_path, vol):
    raw = json.load(open(json_path))
    sess, fwd = raw.get("Session", {}), raw["Forward"]
    src, dom = raw["Optode"]["Source"], raw["Domain"]

    # removed volume builder from original claude input

    cfg = {
        "nphoton":    sess.get("Photons", 1e6),
        "vol":        vol,
        "tstart":     fwd["T0"],
        "tend":       fwd["T1"],
        "tstep":      fwd["Dt"],
        "srcpos":     src["Pos"][:3],
        "srcdir":     src["Dir"][:3],
        "srctype":    src.get("Type", "pencil"),
        "prop":       [[m["mua"], m["mus"], m["g"], m["n"]] for m in dom["Media"]],
        "unitinmm":   dom.get("LengthUnit", 1),
        "issrcfrom0": dom.get("OriginType", 1),
    }
    if "RNGSeed" in sess:
        cfg["seed"] = sess["RNGSeed"]
    for p in ("Param1", "Param2"): # only added if present
        if p in src:
            cfg["srcparam" + p[-1]] = src[p]

    return cfg
