import json
import numpy as np
import matplotlib.pyplot as plt

# function generated by Claude Opus 4.8
# detailed in /docs/prompts, "Asked to build load_mcx_config in scripts/utils.py"
def load_mcx_config(json_path, vol):
    raw = json.load(open(json_path))
    sess, fwd = raw.get("Session", {}), raw["Forward"]
    src, dom = raw["Optode"]["Source"], raw["Domain"]

    # removed volume builder from original claude input

    cfg = {
        "nphoton":    sess.get("Photons", 1e6),
        "vol":        vol,
        "tstart":     fwd["T0"],
        "tend":       fwd["T1"],
        "tstep":      fwd["Dt"],
        "srcpos":     src["Pos"][:3],
        "srcdir":     src["Dir"][:3],
        "srctype":    src.get("Type", "pencil"),
        "prop":       [[m["mua"], m["mus"], m["g"], m["n"]] for m in dom["Media"]],
        "unitinmm":   dom.get("LengthUnit", 1),
        "issrcfrom0": dom.get("OriginType", 1),
    }
    if "RNGSeed" in sess:
        cfg["seed"] = sess["RNGSeed"]
    for p in ("Param1", "Param2"): # only added if present
        if p in src:
            cfg["srcparam" + p[-1]] = src[p]

    return cfg

# function generated by Claude Opus 4.8
# detailed in docs/prompts, "Asked to build graph_flux_3d"
def graph_flux_3d(file_path):
    flux = np.load(file_path)
    if flux.ndim == 4:
        flux = flux[..., 0]

    # log scale (flux decays exponentially with depth)
    logflux = np.log10(flux + 1e-8)

    # pick a threshold to only show voxels with meaningful signal
    threshold = np.percentile(logflux, 90)
    filled = logflux > threshold

    # normalize for coloring
    norm = (logflux - logflux[filled].min()) / (logflux[filled].max() - logflux[filled].min())
    colors = plt.cm.viridis(np.clip(norm, 0, 1))
    colors[..., 3] = np.where(filled, 0.6, 0)  # alpha only where filled

    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(projection='3d')
    ax.voxels(filled, facecolors=colors, edgecolor=None)
    ax.set_xlabel('x');
    ax.set_ylabel('y');
    ax.set_zlabel('z')
    plt.tight_layout()
    plt.show()
